### PR TITLE
use IncludeMSBuildGitHashInfoVersion to skip out on setting AssemblyI…

### PR DESCRIPTION
**Pull request by drdamour**
…nformationalVersionAttribute

for #15

### CODE REVIEW

**Comment by drdamour** [comment]
not sure how to test msbuild targets, never done it before or if this breaks your tests

**Review by MarkPflug — COMMENTED** [review]
While I agree with the idea, I can't accept this change as it is. This is essentially adding an "opt-in" to the informational version, which would be a breaking change for existing users. Instead, it would be acceptable to change the conditional logic so that it would be possible to opt-out instead.

**Comment by drdamour** [comment]
@MarkPflug it's not an opt in, the existing line https://github.com/MarkPflug/MSBuildGitHash/pull/16/files#diff-0c92ae70ea3f001f520d68c6f14ffda4R5 defaults it true, it's only opt out

**Comment by MarkPflug** [comment]
Ah perfect. I didn't see that because it was already there. Based on that, it appears that I had intended to do this, but just didn't wire it up.

**Pull request merged**
